name: Deploy VPS

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Pull & Run VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            IMAGE="ghcr.io/${{ github.repository_owner }}/concordiasite:${{ github.event.workflow_run.head_sha }}"
            NET="proxy-net"

            docker network inspect "$NET" >/dev/null 2>&1 || docker network create "$NET"

            docker pull "$IMAGE"

            docker stop site-vitrine || true
            docker rm site-vitrine || true

            docker run -d \
              --name site-vitrine \
              --restart unless-stopped \
              --network "$NET" \
              -p 8080:80 \
              "$IMAGE"

            docker ps | grep site-vitrine